// Auto-generated by train_lstm.py — do not edit manually
// Apply these before feeding raw sensor data into the LSTM input buffer.
//
// Normalised value = (raw - FEAT_MIN[i]) / (FEAT_MAX[i] - FEAT_MIN[i])
// Denormalised HR  = predicted * (HR_MAX - HR_MIN) + HR_MIN

#pragma once

// Feature order: [Acc_X, Acc_Y, Acc_Z, PPG_Raw]
constexpr float FEAT_MIN[4] = {
  -0.738752f,  // Acc_X
  -2.040743f,  // Acc_Y
  -0.211476f,  // Acc_Z
  237.749011f   // PPG_Raw
};

constexpr float FEAT_MAX[4] = {
  1.553012f,  // Acc_X
  0.710745f,  // Acc_Y
  1.966225f,  // Acc_Z
  1097.089592f   // PPG_Raw
};

// Heart-rate denormalisation
constexpr float HR_MIN = 70.0f;
constexpr float HR_MAX = 74.0f;

// Inline helper — normalise one feature value
inline float normalise(float raw, int feat_idx) {
  float range = FEAT_MAX[feat_idx] - FEAT_MIN[feat_idx];
  if (range < 1e-6f) return 0.0f;
  return (raw - FEAT_MIN[feat_idx]) / range;
}

// Inline helper — convert raw LSTM output [0,1] back to bpm
inline float denormalise_hr(float pred) {
  return pred * (HR_MAX - HR_MIN) + HR_MIN;
}
